name: E-commerce NextJS Application

on:
  push:
    branches: [main]

jobs:
  build-e-commerce:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS # for setup
        uses: actions/setup-node@v4 # For action we have to use uses
        with:
          node-version: 18.x # parameters with node version

        # install dependencies
      - name: install dependencies
        run: npm install

      - name: Build
        run: yarn build

      - run: npm run export
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .next # The folder the action should deploy.
