name: E-commerce NextJS Application

on:
  push:
    branches: [main]

jobs:
  build-e-commerce:
    run-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4

      - name: Setup NodeJS # for setup
        uses: action/setup-node@v4 # For action we have to use uses
        with: node-version:18.x # parameters with node version

        # install dependencies
      - name: install dependencies
        run: npm install

      - name: Build
        run: npm run build
